\d gp_transaction_log
\d gp_distributed_xacts
\d gp_pgdatabase
\d pg_exttable
\d gp_distributed_log
\d pg_largeobject
\d relation_tag_descriptions
\d schema_tag_descriptions
\d tablespace_tag_descriptions
\d user_tag_descriptions
\d database_tag_descriptions
\d gp_suboverflowed_backend
\d pg_user_mappings
\d pg_stat_progress_copy
\d pg_stat_progress_basebackup
\d pg_stat_progress_create_index
\d pg_stat_progress_cluster
\d pg_stat_progress_vacuum
\d pg_stat_progress_analyze
\d pg_stat_wal
\d pg_stat_bgwriter
\d gp_session_endpoints
\d gp_segment_endpoints
\d gp_endpoints
\d gp_stat_archiver
\d pg_stat_archiver
\d pg_stat_xact_user_functions
\d pg_stat_user_functions
\d pg_stat_database_conflicts
\d pg_resqueue_attributes
\d pg_stat_operations
\d pg_max_external_files
\d pg_resqueue_status
\d pg_stat_resqueues
\d pg_stat_database
\d pg_stat_replication_slots
\d pg_replication_slots
\d pg_stat_gssapi
\d pg_stat_ssl
\d pg_stat_subscription
\d pg_stat_wal_receiver
\d pg_stat_slru
\d gp_stat_replication
\d gp_settings
\d gp_stat_activity
\d pg_stat_replication
\d pg_stat_activity_extended
\d pg_stat_activity
\d pg_statio_user_sequences
\d pg_statio_sys_sequences
\d pg_statio_all_sequences
\d pg_statio_user_indexes
\d pg_statio_sys_indexes
\d pg_statio_all_indexes
\d pg_stat_user_indexes
\d pg_stat_sys_indexes
\d pg_stat_all_indexes
\d pg_stat_all_indexes_internal
\d pg_statio_user_tables
\d pg_statio_sys_tables
\d pg_statio_all_tables
\d pg_stat_xact_user_tables
\d pg_stat_user_tables_single_node
\d pg_stat_user_tables
\d pg_stat_xact_sys_tables
\d pg_stat_sys_tables_single_node
\d pg_stat_sys_tables
\d pg_stat_xact_all_tables
\d pg_stat_all_tables
\d pg_stat_all_tables_internal
\d pg_timezone_names
\d pg_timezone_abbrevs
\d pg_seclabels
\d pg_prepared_statements
\d pg_prepared_xacts
\d pg_available_extension_versions
\d pg_available_extensions
\d pg_cursors
\d pg_locks
\d pg_publication_tables
\d pg_stats_ext_exprs
\d pg_stats_ext
\d pg_stats
\d pg_sequences
\d pg_indexes
\d pg_matviews
\d pg_tables
\d pg_views
\d pg_rules
\d pg_policies
\d pg_user
\d pg_group
\d pg_roles
\d gp_segment_configuration
\d gp_matview_tables
\d gp_matview_aux
\d pg_tag_description
\d pg_tag
\d gp_storage_server
\d pg_directory_table
\d pg_profile
\d pg_task_run_history
\d pg_task
\d gp_partition_template
\d pg_subscription_rel
\d pg_publication_rel
\d pg_publication
\d pg_sequence
\d pg_transform
\d pg_range
\d pg_partitioned_table
\d pg_collation
\d pg_shseclabel
\d pg_seclabel
\d pg_init_privs
\d pg_default_acl
\d pg_replication_origin
\d pg_policy
\d pg_foreign_table_seg
\d pg_foreign_table
\d pg_stat_last_shoperation
\d pg_stat_last_operation
\d pg_type_encoding
\d pg_proc_callback
\d pg_compression
\d pg_auth_time_constraint
\d pg_attribute_encoding
\d pg_extprotocol
\d gp_fastsequence
\d pg_appendonly
\d gp_warehouse
\d gp_version_at_initdb
\d gp_distribution_policy
\d gp_id
\d gp_configuration_history
\d pg_resgroupcapability
\d pg_resgroup
\d pg_resourcetype
\d pg_resqueuecapability
\d pg_resqueue
\d pg_foreign_server
\d pg_foreign_data_wrapper
\d pg_extension
\d pg_ts_template
\d pg_ts_parser
\d pg_ts_dict
\d pg_ts_config_map
\d pg_ts_config
\d pg_shdescription
\d pg_shdepend
\d pg_auth_members
\d pg_tablespace
\d pg_db_role_setting
\d pg_depend
\d pg_conversion
\d pg_namespace
\d pg_enum
\d pg_cast
\d pg_description
\d pg_event_trigger
\d pg_trigger
\d pg_rewrite
\d pg_statistic_ext
\d pg_aggregate
\d pg_largeobject_metadata
\d pg_language
\d pg_amproc
\d pg_amop
\d pg_am
\d pg_opclass
\d pg_opfamily
\d pg_operator
\d pg_index
\d pg_inherits
\d pg_constraint
\d pg_attrdef
\d pg_class
\d pg_proc
\d pg_attribute
\d pg_type
\d pg_password_history
\d pg_subscription
\d pg_replication_origin_status
\d gp_storage_user_mapping
\d pg_user_mapping
\d pg_database
\d pg_backend_memory_contexts
\d pg_shmem_allocations
\d pg_config
\d pg_hba_file_rules
\d pg_file_settings
\d pg_settings
\d pg_statistic_ext_data
\d pg_statistic
\d pg_shadow
\d pg_authid

